version: "3.4"

services:
  presentation:
    image: ${DOCKER_REGISTRY-}presentationlayer
    build:
      context: .
      dockerfile: PresentationLayer/Dockerfile
    environment:
      ConnectionStrings__Bachelor:
    depends_on:
      - db
    secrets:
      - source: connection_string
        target: ConnectionStrings__Bachelor
  db:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 3306:3306
    secrets:
      - db_password
secrets:
  db_password:
    file: ./.local/db_password.txt
  connection_string:
    file: ./.local/connection_string.txt
