// <auto-generated />
using System;
using DomainLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DomainLayer.Migrations
{
    [DbContext(typeof(BachelorDbContext))]
    [Migration("20230406092126_UpdateSeedDate")]
    partial class UpdateSeedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomainLayer.Documentation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TestFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("TestFileId")
                        .IsUnique();

                    b.ToTable("Documentation");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0427d31b-5d96-449b-b420-ddaadceaefb2"),
                            CreatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 302, DateTimeKind.Utc).AddTicks(9600),
                            Summary = "Jeg er et summary",
                            TestFileId = new Guid("6ea2fe17-3be2-4990-aa44-d233698ac483"),
                            Translation = "Jeg er en translation",
                            UpdatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 302, DateTimeKind.Utc).AddTicks(9600)
                        });
                });

            modelBuilder.Entity("DomainLayer.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitRepoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GitRepoOwner")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("GitRepoName", "GitRepoOwner")
                        .IsUnique();

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bfaf6610-6eaf-4bf2-8d08-eadaf01d2fd6"),
                            CreatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(570),
                            Description = "Dette er en beskrivelse",
                            GitRepoName = "Repo1",
                            GitRepoOwner = "OwnerJens",
                            Title = "Project 1",
                            UpdatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(570)
                        },
                        new
                        {
                            Id = new Guid("d91cc4d8-f22a-4aa9-841d-3f8540c01f29"),
                            CreatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(570),
                            Description = "Dette er en beskrivelse",
                            GitRepoName = "Repo2",
                            GitRepoOwner = "OwnerBo",
                            Title = "Project 2",
                            UpdatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(570)
                        },
                        new
                        {
                            Id = new Guid("ac2493fc-1a2f-4462-9707-86968b937254"),
                            CreatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(570),
                            Description = "Dette er en beskrivelse",
                            GitRepoName = "Repo3",
                            GitRepoOwner = "OwnerBo",
                            Title = "Project 3",
                            UpdatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(570)
                        },
                        new
                        {
                            Id = new Guid("2d11a37e-9f9a-485d-9921-346c19b59e7b"),
                            CreatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(570),
                            Description = "Dette er en beskrivelse",
                            GitRepoName = "Repo4",
                            GitRepoOwner = "OwnerBo",
                            Title = "Project 4",
                            UpdatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(570)
                        },
                        new
                        {
                            Id = new Guid("8bf19e4d-3abf-4504-8fbb-65d50a2cfd9e"),
                            CreatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(570),
                            Description = "Dette er en beskrivelse",
                            GitRepoName = "Repo5",
                            GitRepoOwner = "OwnerBo",
                            Title = "Project 5",
                            UpdatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(570)
                        });
                });

            modelBuilder.Entity("DomainLayer.TestFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TestFiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee61a729-a960-467a-bdc1-1d7184ee7346"),
                            Content = "Jeg er et script content",
                            CreatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(2660),
                            Name = "TestFile 1",
                            Path = "somePath",
                            ProjectId = new Guid("bfaf6610-6eaf-4bf2-8d08-eadaf01d2fd6"),
                            UpdatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(2660)
                        },
                        new
                        {
                            Id = new Guid("6ea2fe17-3be2-4990-aa44-d233698ac483"),
                            Content = "Jeg er også et script",
                            CreatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(2660),
                            Name = "TestFile 2",
                            Path = "somePath2",
                            ProjectId = new Guid("bfaf6610-6eaf-4bf2-8d08-eadaf01d2fd6"),
                            UpdatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(2660)
                        },
                        new
                        {
                            Id = new Guid("21444a04-eea6-4d61-84b6-2d260463a923"),
                            Content = "Jeg er også et script",
                            CreatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(2660),
                            Name = "TestFile 3",
                            Path = "somePath3",
                            ProjectId = new Guid("bfaf6610-6eaf-4bf2-8d08-eadaf01d2fd6"),
                            UpdatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(2660)
                        },
                        new
                        {
                            Id = new Guid("19528834-83ea-44f2-8beb-594300d0e9e1"),
                            Content = "Jeg er også et script",
                            CreatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(2680),
                            Name = "TestFile 4",
                            Path = "somePath4",
                            ProjectId = new Guid("bfaf6610-6eaf-4bf2-8d08-eadaf01d2fd6"),
                            UpdatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(2680)
                        },
                        new
                        {
                            Id = new Guid("5d4e7b0d-3ff2-4ffd-abb6-1e0583731a23"),
                            Content = "Jeg er også et script",
                            CreatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(2680),
                            Name = "TestFile 5",
                            Path = "somePath5",
                            ProjectId = new Guid("d91cc4d8-f22a-4aa9-841d-3f8540c01f29"),
                            UpdatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(2680)
                        },
                        new
                        {
                            Id = new Guid("8301384b-0d85-4f87-bcd5-367f5320a2d3"),
                            Content = "Jeg er også et script",
                            CreatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(2690),
                            Name = "TestFile 6",
                            Path = "somePath6",
                            ProjectId = new Guid("d91cc4d8-f22a-4aa9-841d-3f8540c01f29"),
                            UpdatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(2690)
                        });
                });

            modelBuilder.Entity("DomainLayer.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("596bd00e-8699-4183-850f-14dc879bf9d8"),
                            CreatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(3330),
                            Email = "Jens@gmail.com",
                            Name = "Jens",
                            Password = "1234"
                        },
                        new
                        {
                            Id = new Guid("5f6bd9e2-569f-40ea-8f27-79f3b87e1638"),
                            CreatedDate = new DateTime(2023, 4, 6, 9, 21, 26, 303, DateTimeKind.Utc).AddTicks(3330),
                            Email = "Bo@gmail.com",
                            Name = "Bo",
                            Password = "1234"
                        });
                });

            modelBuilder.Entity("ProjectUser", b =>
                {
                    b.Property<Guid>("ProjectsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjectsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UsersProject", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectsId = new Guid("bfaf6610-6eaf-4bf2-8d08-eadaf01d2fd6"),
                            UsersId = new Guid("596bd00e-8699-4183-850f-14dc879bf9d8")
                        },
                        new
                        {
                            ProjectsId = new Guid("bfaf6610-6eaf-4bf2-8d08-eadaf01d2fd6"),
                            UsersId = new Guid("5f6bd9e2-569f-40ea-8f27-79f3b87e1638")
                        },
                        new
                        {
                            ProjectsId = new Guid("d91cc4d8-f22a-4aa9-841d-3f8540c01f29"),
                            UsersId = new Guid("596bd00e-8699-4183-850f-14dc879bf9d8")
                        },
                        new
                        {
                            ProjectsId = new Guid("d91cc4d8-f22a-4aa9-841d-3f8540c01f29"),
                            UsersId = new Guid("5f6bd9e2-569f-40ea-8f27-79f3b87e1638")
                        },
                        new
                        {
                            ProjectsId = new Guid("ac2493fc-1a2f-4462-9707-86968b937254"),
                            UsersId = new Guid("596bd00e-8699-4183-850f-14dc879bf9d8")
                        },
                        new
                        {
                            ProjectsId = new Guid("2d11a37e-9f9a-485d-9921-346c19b59e7b"),
                            UsersId = new Guid("596bd00e-8699-4183-850f-14dc879bf9d8")
                        },
                        new
                        {
                            ProjectsId = new Guid("8bf19e4d-3abf-4504-8fbb-65d50a2cfd9e"),
                            UsersId = new Guid("596bd00e-8699-4183-850f-14dc879bf9d8")
                        });
                });

            modelBuilder.Entity("DomainLayer.Documentation", b =>
                {
                    b.HasOne("DomainLayer.TestFile", "TestFile")
                        .WithOne("Documentation")
                        .HasForeignKey("DomainLayer.Documentation", "TestFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestFile");
                });

            modelBuilder.Entity("DomainLayer.TestFile", b =>
                {
                    b.HasOne("DomainLayer.Project", "Project")
                        .WithMany("TestFiles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectUser", b =>
                {
                    b.HasOne("DomainLayer.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DomainLayer.Project", b =>
                {
                    b.Navigation("TestFiles");
                });

            modelBuilder.Entity("DomainLayer.TestFile", b =>
                {
                    b.Navigation("Documentation");
                });
#pragma warning restore 612, 618
        }
    }
}
